### ISSUE TITLE
Paths need escaping for auto-import.

### ISSUE THREAD

**Issue by patrickgreenwell** [chfritz/meteor-gtfs#1]
When using the windows version of meteor, paths contain `\` which are escaped.  So a Path like
`D:\Source\Repos\application\server\X.gtfs.zip` becomes `D:SourceReposapplicationserverX.gtfs.zip`

If you have a workaround I'm not sure how to run a package locally but I'll see if I can modify and submit a PR.

**Comment by chfritz** [comment]
A PR would be great! To develop a package locally, you can just create a folder `packages` in your meteor project directory and place the package folder in there using the same name (`chfritz:gtfs`). Once you have that in place, meteor will use that instead of the one installed from atmosphere -- at least that's how it works _before_ ever installing the package from atmosphere.

**Comment by patrickgreenwell** [comment]
Thanks I'll try it out!

Patrick Greenwell

**Comment by chfritz** [comment]
I think, all you may need to do is to double-escape `\`s in the second argument of https://github.com/chfritz/meteor-gtfs/blob/master/plugin/import-gtfs.js#L56. But I'm not sure and can't test this very easily without a windows machine.
